services:
  api:
    container_name: api
    build:
      context: .
      target: production
    ports:
      - 80:3000
# # Uncomment or passing as environment variables
#    env_file:
#      - .env
#      - .docker.env
